### ISSUE TITLE
Request: ability to add modded items to existing categories

### ISSUE THREAD

**Issue by GizmoTheMoonPig** [immortius/museumcurator#1]
Hello! Happened to stumble across this mod when browsing through recently updated mods a bit ago and I'm really happy you made this! I had the idea to make a mod similar to this for a while, but you beat me to it haha. 

Anyway, I'm a developer of a few big-name mods, mainly Rats and Twilight Forest. I would absolutely love to add built-in compatibility for this mod to my various projects, my main stopper at the moment is not being able to add my items to existing categories. 

## Example:
Twilight Forest adds 8 new wood types. Instead of creating a new checklist category for these, I would love to add them to the currently existing Botany category without replacing the entire page. It would be absolutely lovely if I could specify where the group goes on the page, however if that's too much work I totally understand. 
I would also like to add our doors, trapdoors, signs, etc to the existing categories in the Architecture tab. I don't really care so much about ordering on this one, but it may also be a nice addition if you're feeling up to it. 

I think the best way to do this would be to "merge" the jsons if another modid has a file that's named the same as one of yours and the "name" field is the same. For example, if I added a json similar to this file I whipped up ([botany.json](https://gist.github.com/GizmoTheMoonPig/4bd8e85b9f83af54f6660042c228f672)) under `data/twilightforest/museumcollection` it would automatically take the contents and merge them into the existing category.

Since `museumcurator.twilightforest.twilightOakTree` isn't used as a name by any of your entries it would create a new entry with all of the items listed. `museumcurator.botany.flowers` is an existing entry though so the contents of that would be added to the existing entry. 

## 

I'm unfortunately a little short on time these days, otherwise I would 100% make a PR to do this. If I find a good chunk of time to do this, I absolutely will though. Appreciate you hearing me out!

**Comment by immortius** [comment]
Sounds reasonable, I'll have a go at adding this once I've finished updating Chunk By Chunk to 1.20.1.

**Comment by immortius** [comment]
So, what I'm thinking about is to switch from collection-level files to exhibit-level files, and then have the following format:
```json
{
  "collection" : "museumcurator.collection.animalhusbandry",
  "name" : "museumcurator.animalhusbandry.beestuff",
  "relativeTo" : "museumcurator.animalhusbandry.pigstuff",
  "placement" : "after",
  "items" : [
    "minecraft:beehive",
    {
      "id" : "minecraft:potion",
      "tags" : {
        "Potion" : "minecraft:long_slow_falling"
      }
    }  
  ],
  "insertGroups" : [
    {
      "relativeTo" : "minecraft:beehive",
      "placement" : "before",
      "items" : [
         "minecraft:honeycomb",
         "minecraft:honeycomb_block"
      ]
    }
  ] 
}
```

"relativeTo", "placement", "items" and "insertGroups" are all optional, with placement defaulting to after. All files adding to the same collection + exhibit name will be merged, then the insert groups merged into the item list applying their placement rules if specified. Finally exhibits will be combined into collections again following placement rules. I think this should give the desired flexibility.

**Comment by GizmoTheMoonPig** [comment]
that is insanely beautiful. This system would be lovely to work with! Thank you so much for taking the time to do this

**Comment by immortius** [comment]
Released in 1.3.0

**Comment by Zunwolf1896** [comment]
sorry, can you explain, or make a template datapack that I can edit to add a bunch of the mods I have into it?

**Comment by immortius** [comment]
Firstly I should mention that you need both a data pack and an asset pack for the text strings, which is perhaps a bit awkward. 

All the existing exhibits and collections are found under https://github.com/immortius/museumcurator/tree/main/Common/src/main/resources/data/museumcurator/museumexhibits
which should give you an idea of the datapack structure and the format of the files. The path in a datapack would then be data/<packid>/museumexhibits. Each json file describes an exhibit, and one or more exhibits is part of a collection (collections are the button when you first open the clipboard). To create a new collection you just create an exhibit that uses a new collection. The "collection" and "name" attributes are the ids of strings from a language file (so that's where the asset pack comes in). The items in the collection specify what to include, for most items just their id is enough, but if needed tags can be specified.

If you have any more specific questions feel free to ask.
